language: python

python:
  - pypy3
  - pypy
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - 2.7
  - 2.6

sudo: false

install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then travis_retry pip install unittest2; fi

  # Coverage 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then pip install "coverage<4"; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then pip install coverage; fi

  - travis_retry python setup.py install
  - travis_retry pip install coveralls

script:
  - coverage run --include=pycorpora/* tests/test_pycorpora.py

after_success:
    # Report coverage and send to coveralls.io
  - coverage report
  - coveralls

    # Static analysis
  - travis_retry pip install pycodestyle pyflakes
  - pyflakes . | tee >(wc -l)
  - pycodestyle --statistics --count .


matrix:
  fast_finish: true
