language: python

matrix:
  fast_finish: true
  include:
    - python: pypy3
    - python: pypy
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: 3.5
    - python: 2.7

install:
  - travis_retry pip install coverage
  - travis_retry python setup.py install

script:
  - coverage run --include=pycorpora/* tests/test_pycorpora.py

after_success:
    # Report coverage and send to coveralls.io
  - coverage report
  - pip install coveralls && coveralls

    # Static analysis
  - travis_retry pip install pycodestyle pyflakes
  - pyflakes . | tee >(wc -l)
  - pycodestyle --statistics --count .
